# Get the current time in HH:MM:SS format
CURRENT_TIME=$(date +"%Y-%m-%d %H:%M:%S")

# Print the current time
echo "Current Time: $CURRENT_TIME"

# Define the prepending string to generated source files
PREPEND_STRING="//////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////
// THIS IS A GENERATED SOURCE FILE,
// DO NOT EDIT THIS FILE OR YOUR CHANGES WILL BE LOST.
// GENERATION TIME: $CURRENT_TIME
//////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////

"

# Copy the common files to all projects (generating source files)
./dst-src.sh ../src/common ../src/bv-glasses-project "$PREPEND_STRING"

